ProspectRealEstate.Web/Models/Extensions/Property.cs
using ProspectRealEstate.Web.Helpers;
using ProspectRealEstate.Web.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;

namespace ProspectRealEstate.Web.Models
{
    public partial class Property
    {
        public PropertyListModel ToListModel()
        {
            var slug = this.description;
            if (this.description.Length > 250)
                slug = this.description.Substring(0, 247) + "...";

            var listModel = new PropertyListModel()
            {
                ID = this.ID,
                Title = String.Join(",", this.street, this.Suburb.name),
                Description = slug,
                IsFeatured = this.featured,
                NumOfBathroom = this.num_of_bathroom.ToString("##"),
                NumOfBedroom = this.num_of_bedroom.ToString("##"),
                NumOfCarspace = this.num_of_carspace.ToString("##"),
                Price = StringHelper.ParsePriceRange(this.min_price, this.max_price),
                AddedOn = this.added_on,
                Status = this.status
            };

            if (this.Attachments.Count > 0)
            {
                listModel.ThumbnailFilePath = this.Attachments.First().file_location;

                var featuredFilePath = this.Attachments.FirstOrDefault(
                    a => Path.GetFileNameWithoutExtension(a.file_location).ToLower().StartsWith("featured"));

                if (featuredFilePath != null)
                    listModel.FeaturedPhoto = featuredFilePath.file_location;
                else
                    listModel.FeaturedPhoto = listModel.ThumbnailFilePath;
            }

            return listModel;
        }

        public string PriceRange
        {
            get { return StringHelper.ParsePriceRange(this.min_price, this.max_price); }
        }
    }
}

ProspectRealEstate.Web/Models/Property.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProspectRealEstate.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        public Property()
        {
            this.Attachments = new HashSet<Attachment>();
        }
    
        public int ID { get; set; }
        public string property_code { get; set; }
        public byte property_type { get; set; }
        public byte num_of_bedroom { get; set; }
        public byte num_of_bathroom { get; set; }
        public byte num_of_carspace { get; set; }
        public Nullable<int> land_area { get; set; }
        public string description { get; set; }
        public bool featured { get; set; }
        public string street { get; set; }
        public short suburb_id { get; set; }
        public byte state_id { get; set; }
        public short country_id { get; set; }
        public string postcode { get; set; }
        public Nullable<int> min_price { get; set; }
        public Nullable<int> max_price { get; set; }
        public System.Data.Spatial.DbGeography latlng { get; set; }
        public Nullable<byte> agent_id { get; set; }
        public System.DateTime added_on { get; set; }
        public byte added_by { get; set; }
        public Nullable<System.DateTime> modified_on { get; set; }
        public Nullable<byte> modified_by { get; set; }
        public string status { get; set; }
        public string rent_or_sale { get; set; }
        public byte lang { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual ICollection<Attachment> Attachments { get; set; }
        public virtual Country Country { get; set; }
        public virtual PropertyType PropertyType { get; set; }
        public virtual State State { get; set; }
        public virtual Suburb Suburb { get; set; }
        public virtual User AddedBy { get; set; }
        public virtual User ModifiedBy { get; set; }
        public virtual Language Language { get; set; }
    }
}

ProspectRealEstate.Web/Models/PropertyType.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProspectRealEstate.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyType
    {
        public PropertyType()
        {
            this.Properties = new HashSet<Property>();
        }
    
        public byte ID { get; set; }
        public string name { get; set; }
        public byte added_by { get; set; }
        public System.DateTime added_on { get; set; }
        public Nullable<byte> modified_by { get; set; }
        public Nullable<System.DateTime> modified_on { get; set; }
        public byte lang { get; set; }
    
        public virtual ICollection<Property> Properties { get; set; }
        public virtual User AddedBy { get; set; }
        public virtual User ModifiedBy { get; set; }
        public virtual Language Language { get; set; }
    }
}

ProspectRealEstate.Web/Controllers/PropertyController.cs
using ProspectRealEstate.Web.Filters;
using ProspectRealEstate.Web.Models;
using ProspectRealEstate.Web.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using System.IO;
using System.Globalization;
using System.Text.RegularExpressions;
using System.Net.Mail;

namespace ProspectRealEstate.Web.Controllers
{
    [HandleCulture]
    public class PropertyController : Controller
    {
        IPropertyRepository repository;
        CommonRepository commons;
        AgentRepository agentRepository;

        private SmtpClient client = new SmtpClient() { EnableSsl = true };

        private const int PAGE_SIZE = 10;

        public PropertyController()
        {
            repository = new PropertyRepository();
            commons = new CommonRepository();
            agentRepository = new AgentRepository();
        }

        public ActionResult Index(int? page)
        {
            return RedirectToAction("Sale", new { page = page });
        }

        public ActionResult Sale(int? page, string sortOrder)
        {
            ViewBag.SortParam = sortOrder;
            SetSearchViewBag();
            var models = from m in repository.All
                         where m.rent_or_sale.ToLower() == @"sale" &&
                               m.Language.LanguageName == CultureInfo.CurrentUICulture.Name
                         select m;

            switch (sortOrder)
            {
                case "hp":
                    models = models.OrderByDescending(p => p.min_price);
                    break;
                case "lp":
                    models = models.OrderBy(p => p.min_price);
                    break;
                default:
                    models = models.OrderByDescending(p => p.added_on);
                    break;
            }

            var listModels = models.AsEnumerable().Select(p => p.ToListModel());
            var pageNumber = page ?? 1;
            return View("Index", listModels.ToPagedList(pageNumber, PAGE_SIZE));
        }

        public ActionResult Rent(int? page, string sortOrder)
        {
            ViewBag.SortParam = sortOrder;
            SetSearchViewBag();
            var models = from m in repository.All
                         where m.rent_or_sale.ToLower() == @"rent" &&
                               m.Language.LanguageName == CultureInfo.CurrentUICulture.Name
                         select m;

            switch (sortOrder)
            {
                case "hp":
                    models = models.OrderByDescending(p => p.min_price);
                    break;
                case "lp":
                    models = models.OrderBy(p => p.min_price);
                    break;
                default:
                    models = models.OrderByDescending(p => p.added_on);
                    break;
            }

            var listModels = models.AsEnumerable().Select(p => p.ToListModel());
            var pageNumber = page ?? 1;
            return View("Index", listModels.ToPagedList(pageNumber, PAGE_SIZE));
        }

        public ActionResult Search(PropertySearchModel sm, int? page, string sortOrder)
        {
            ViewBag.SortParam = sortOrder;
            SetSearchViewBag();
            var models = from m in repository.FindBySearchModel(sm)
                         where m.Language.LanguageName == CultureInfo.CurrentUICulture.Name
                         select m;

            switch (sortOrder)
            {
                case "hp":
                    models = models.OrderByDescending(p => p.min_price);
                    break;
                case "lp":
                    models = models.OrderBy(p => p.min_price);
                    break;
                default:
                    models = models.OrderByDescending(p => p.added_on);
                    break;
            }

            var listModels = models.AsEnumerable().Select(p => p.ToListModel());
            var pageNumber = page ?? 1;
            return View("Index", listModels.ToPagedList(pageNumber, PAGE_SIZE));
        }

        [NoMembershipAuthorize]
        public ActionResult Admin(int? page, string sortOrder, string language)
        {
            var all = repository.All;

            // Apply language filter
            if (language != "all" && !String.IsNullOrEmpty(language))
            {
                if (language == "en")
                    all = all.Where(b => b.Language.LanguageName == "en-AU");
                else
                    all = all.Where(b => b.Language.LanguageName == "zh-CN");
            }

            // Apply sorter
            ViewBag.TitleSortParam = String.IsNullOrEmpty(sortOrder) ? "td" : "";
            ViewBag.DateSortParam = sortOrder == "da" ? "dd" : "da";
            switch (sortOrder)
            {
                case "td":
                    all = all.OrderByDescending(m => m.street);
                    break;
                case "da":
                    all = all.OrderBy(m => m.added_on);
                    break;
                case "dd":
                    all = all.OrderByDescending(m => m.added_on);
                    break;
                default:
                    all = all.OrderBy(m => m.street);
                    break;
            }

            var models = all.AsEnumerable().Select(p => p.ToListModel());
            var pageNumber = page ?? 1;
            return View("AdminIndex", models.ToPagedList(pageNumber, PAGE_SIZE));
        }

        [NoMembershipAuthorize]
        public ActionResult Create()
        {
            var model = new Property();
            SetViewBag(model);
            return View(model);
        }

        [HttpPost, NoMembershipAuthorize]
        public ActionResult Create(Property model, IEnumerable<HttpPostedFileBase> attachments)
        {
            var cusr = Session["_CUSR"] as SessionUser;
            if (cusr == null) throw new ArgumentException("SessionUser");

            model.added_by = (byte)cusr.ID;
            model.added_on = DateTime.Now;

            try
            {
                if (attachments != null)
                {
                    foreach (var item in attachments)
                    {
                        if (item != null && item.ContentLength > 0)
                        {
                            var filename = Path.GetFileName(item.FileName).ToLower();
                            var dirpath = "~/Uploads/Property/" + GetFolderName(model);
                            var directory = Server.MapPath(dirpath);

                            if (!Directory.Exists(directory))
                                Directory.CreateDirectory(directory);

                            string path = Path.Combine(directory, filename);
                            string relPath = Path.Combine(dirpath, filename);
                            item.SaveAs(path);

                            model.Attachments.Add(new ProspectRealEstate.Web.Models.Attachment()
                            {
                                added_by = (byte)cusr.ID,
                                added_on = DateTime.Now,
                                Property = model,
                                file_location = relPath,
                                type = "image"
                            });
                        }
                    }
                }

                ModelState.Remove("Attachments");

                if (ModelState.IsValid)
                {
                    repository.InsertOrUpdate(model);
                    repository.SubmitChanges();
                    return RedirectToAction("Edit", new { id = model.ID });
                }
                else
                {
                    return View();
                }
            }
            catch (Exception ex)
            {
                throw;
            }
        }

        public ActionResult Detail(int id)
        {
            var model = repository.Find(id);
            return View(model);
        }

        [HttpPost]
        public ActionResult SendQuery(SendQueryModel model)
        {
            var emailValidator = new Regex(@"\b[A-Za-z0-9._%-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}\b");
            if (emailValidator.IsMatch(model.UserEmail))
            {
                try
                {
                    var email = new MailMessage(new MailAddress(model.UserEmail), new MailAddress(model.AgentEmail));
                    email.Subject = model.Subject;
                    email.Body = HttpUtility.HtmlEncode(model.Message + "\r\n" + model.UserName + "\r\n" + model.UserEmail);
                    email.IsBodyHtml = false;

                    client.Send(email);
                    return Content("success");
                }
                catch (Exception ex)
                {
                    return Content("error: " + ex.Message);
                }
            }
            return Content("Invalid email address.");
        }

        [NoMembershipAuthorize]
        public ActionResult Edit(int id)
        {
            var model = repository.Find(id);
            SetViewBag(model);
            return View(model);
        }

        [HttpPost, NoMembershipAuthorize]
        public ActionResult Edit(int id, IEnumerable<HttpPostedFileBase> attachments, FormCollection collection)
        {
            var cusr = Session["_CUSR"] as SessionUser;

            var model = repository.Find(id);
            try
            {
                if (attachments != null)
                {
                    foreach (var item in attachments)
                    {
                        if (item != null && item.ContentLength > 0)
                        {
                            var filename = Path.GetFileName(item.FileName).ToLower();
                            var dirpath = "~/Uploads/Property/" + GetFolderName(model);

ProspectRealEstate.Web/Views/Property/AdminIndex.cshtml
@model PagedList.IPagedList<ProspectRealEstate.Web.Models.ViewModels.PropertyListModel>
@{
    ViewBag.Title = "Property management - Prospect Real Estate Admin";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@using (@Html.BeginForm("Admin", null, FormMethod.Get, new { style = "float: left" }))
{
    <label class="radio inline">
        @Html.RadioButton("language", "all", true, new { onclick = "document.forms[0].submit()" })
        All
    </label>
    <label class="radio inline">
        @Html.RadioButton("language", "en", new { onclick = "document.forms[0].submit()" })
        English only
    </label>
    <label class="radio inline">
        @Html.RadioButton("language", "cn", new { onclick = "document.forms[0].submit()" })
        Chinese only
    </label>
}

<div class="submit-button">
    @Html.ActionLink("Add", "Create", null, new { @class = "btn btn-primary pull-right" })
</div>

<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>#</th>
            <th>
                @Html.ActionLink("Title", "Admin", new { sortOrder = ViewBag.TitleSortParam })
            </th>
            <th>
                @Html.ActionLink("Added On", "Admin", new { sortOrder = ViewBag.DateSortParam })
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in @Model)
        {
            <tr>
                <td>
                    @if (item.IsFeatured)
                    {
                        <i class="icon-star"></i>
                    }
                    @item.ID
                </td>
                <td>@item.Title</td>
                <td>@item.AddedOn.ToShortDateString()</td>
                <td>
                    @Html.ActionLink("Edit", "Edit", "Property", new { id = @item.ID }, new { @class = "btn" })
                    @if (item.Status != "archived")
                    {
                        <a class="btn btn-danger archive-button" data-key="@item.ID">Archive</a>
                    }
                    else
                    {
                        <a class="btn btn-success activate-button" data-key="@item.ID">Activate</a>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>
<script type="text/javascript">
    $(function () {
        $('.archive-button').click(function () {
            var $this = $(this)
              , model = {
                  ID: $this.data("key")
              };

            $.ajax({
                url: '/en-AU/Property/SetArchive',
                type: 'POST',
                data: model,
                success: function (result) {
                    if (result === 'success') {
                        $this.attr('class', 'btn btn-success activate-button');
                        $this.text('Activate');
                    }
                }
            });
        });

        $('.activate-button').click(function () {
            var $this = $(this)
              , model = {
                  ID: $this.data("key")
              }

            $.ajax({
                url: '/en-AU/Property/SetActive',
                type: 'POST',
                data: model,
                success: function (result) {
                    if (result === 'success') {
                        $this.attr('class', 'btn btn-danger archive-button');
                        $this.text('Archive');
                    }
                }
            });
        });
    });
</script>

ProspectRealEstate.Web/Views/Property/Create.cshtml
@{
    ViewBag.Title = "Add a new property - Prospect Real Estate Admin";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@Html.Partial("_PropertyForm")

ProspectRealEstate.Web/Views/Property/Edit.cshtml
@model ProspectRealEstate.Web.Models.Property
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@Html.Partial("_PropertyForm")

ProspectRealEstate.Web/Views/Property/Index.cshtml
@model IEnumerable<ProspectRealEstate.Web.Models.ViewModels.PropertyListModel>
@using Resx = ProspectRealEstate.Web.Resources;
@{
    ViewBag.Title = "Properties ";
}

<div class="row">
    <div class="span8">
        <div class="content">
            @if (ViewContext.RouteData.Values["action"].ToString().ToLower() == "sale")
            {
                <h3>@Resx.Property.Sale.PropertiesForSale</h3>
            }
            else
            {
                <h3>@Resx.Property.Rent.PropertiesForRent</h3>
            }
            @if (ViewContext.RouteData.Values["action"].ToString().ToLower() == "sale" ||
                 ViewContext.RouteData.Values["action"].ToString().ToLower() == "rent")
            {
                using (Html.BeginForm(null, null, FormMethod.Get))
                {
                <select name="sortOrder" onchange="document.forms[0].submit()">
                    <option value="">@Resx.Business.Index.SortResults</option>
                    <option value="lp" 
                                @if (ViewBag.SortParam == "lp")
                                { 
                                    @:selected = "selected" 
                                }>@Resx.Business.Index.LowestPrice
                    </option>
                    <option value="hp"
                                @if (ViewBag.SortParam == "hp")
                                { 
                                    @:selected = "selected" 
                                }>@Resx.Business.Index.HighestPrice
                    </option>
                    <option value="date"
                                @if (ViewBag.SortParam == "date")
                                { 
                                    @:selected = "selected" 
                                }>@Resx.Business.Index.Date
                    </option>
                </select>
                }
            }
            else
            {
                <div>
                    <select id="selectSortOrder" name="sortOrder">
                        <option value="">@Resx.Business.Index.SortResults</option>
                        <option value="lp" 
                                @if (ViewBag.SortParam == "lp")
                                { 
                                    @:selected = "selected" 
                                }>@Resx.Business.Index.LowestPrice
                        </option>
                        <option value="hp"
                                @if (ViewBag.SortParam == "hp")
                                { 
                                    @:selected = "selected" 
                                }>@Resx.Business.Index.HighestPrice
                        </option>
                        <option value="date"
                                @if (ViewBag.SortParam == "date")
                                { 
                                    @:selected = "selected" 
                                }>@Resx.Business.Index.Date
                        </option>
                    </select>
                </div>
            }
            <ul class="prop-list">
                @foreach (var item in Model)
                {
                    <li class="list-item">
                        <div class="list-date">
                            <div class="month">@item.AddedOn.Month</div>
                            <div class="day">@item.AddedOn.Day</div>
                        </div>
                        <div class="figure">
                            @if (!String.IsNullOrEmpty(item.ThumbnailFilePath))
                            {
                                <img src="@Url.Content(@item.ThumbnailFilePath)" alt="4:3" width="160" height="120" />
                            }
                            else
                            {
                                <img src="" alt="4:3" width="160" height="120" />
                            }
                        </div>
                        <div class="info">
                            <div class="title">
                                <a href="Detail/@item.ID" class="dtlink">@item.Title</a>
                            </div>
                            <div class="meta">
                                <div class="rooms">
                                    <span class="room bedroom">@item.NumOfBedroom</span>
                                    <span class="room bathroom">@item.NumOfBathroom</span>
                                    <span class="room carspace">@item.NumOfCarspace</span>
                                </div>
                            </div>
                            <div class="price">@item.Price</div>
                            <p class="desc">@item.Description</p>
                        </div>
                        <div class="clearfix"></div>
                    </li>   
                }
            </ul>
            @Html.Partial("Pager")
        </div>
    </div>
    <div class="span4">
        <div class="search-biz">
            <h4 class="section-header">@Resx.Property.Sale.FindAProperty</h4>
            @using (Html.BeginForm("Search", "Property", FormMethod.Get, new { id = "formSearchProperty" }))
            {
                <label>@Resx.Home.Index.Location</label>
                @Html.ListBox("PropertyLocation", ViewBag.Suburbs as MultiSelectList,
                        new
                        {
                            @class = "chzn-select",
                            data_placeholder = "Choose suburbs..."
                        })
                <label>@Resx.Home.Index.RentOrSale</label>
                @Html.DropDownList("RentOrSale", ViewBag.RentOrSale as SelectList, "-- SELECT ONE --")
                <label>@Resx.Home.Index.PropertyType</label>
                @Html.DropDownList("PropertyTypes", ViewBag.PropertyTypes as SelectList, "-- SELECT ONE --")
                <label>@Resx.Property.Sale.PriceRange</label>
                <div style="margin-bottom: 20px;">
                    <span class="input-prepend">
                        <span class="add-on">$</span>
                        @Html.TextBox("MinPrice", null, new { @class = "span1" })
                    </span>
                    <span style="padding: 0 10px; line-height: 30px">to</span>
                    <span class="input-prepend">
                        <span class="add-on">$</span>
                        @Html.TextBox("MaxPrice", null, new { @class = "span1" })
                    </span>
                </div>
                <ul class="rooms">
                    <li>
                        <label>@Resx.Home.Index.Bedroom</label>
                        @Html.TextBox("NumOfBedroom", null, new { @class = "span1" })
                    </li>
                    <li>
                        <label>@Resx.Home.Index.Bathroom</label>
                        @Html.TextBox("NumOfBathroom", null, new { @class = "span1" })
                    </li>
                    <li>
                        <label>@Resx.Home.Index.CarSpace</label>
                        @Html.TextBox("NumOfCarspace", null, new { @class = "span1" })
                    </li>
                </ul>
                <div class="clearfix"></div>
                <input id="searchSortOrder" name="sortOrder" type="hidden" />
                <button type="submit" class="btn btn-primary">@Resx.Home.Index.Search</button>
            }
        </div>
    </div>
    <div id="detail-modal" class="modal hide" data-remote="">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h3 class="modal-title"></h3>
        </div>
        <div class="modal-body"></div>
    </div>
</div>
<script src="@Url.Content("~/Content/js/vendor/chosen.jquery.min.js")"></script>
<link href="@Url.Content("~/Content/css/chosen.css")" rel="stylesheet" type="text/css" />
<script type="text/javascript">
    $('.chzn-select').chosen();

    $(function () {
        $('.dtlink').click(function () {
            var $this = $(this)
              , $modal = $('#detail-modal');

            $('#detail-modal .modal-title').text($this.text());
            $modal.data('remote', $this.attr('href'));
            $modal.modal();

            return false;
        });

        $('#detail-modal').on('hidden', function () {
            $(this).removeData('modal');
        });

        $('#selectSortOrder').change(function () {
            var $this = $(this);
            $('#searchSortOrder').val($this.val());
            $('#formSearchProperty').submit();
        });
    });
</script>