ProspectRealEstate.Web/Controllers/BusinessController.cs
using ProspectRealEstate.Web.Models;
using ProspectRealEstate.Web.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using PagedList;
using System.Globalization;
using ProspectRealEstate.Web.Filters;
using System.IO;
using System.Text.RegularExpressions;
using System.Net.Mail;

namespace ProspectRealEstate.Web.Controllers
{
    [Serializable]
    public class SetArchiveViewModel
    {
        public int ID { get; set; }
    }

    [HandleCulture]
    public class BusinessController : Controller
    {
        IBusinessRepository repository;
        CommonRepository commons;
        AgentRepository agentRepository;

        private SmtpClient client = new SmtpClient() { EnableSsl = true };

        private const int PAGE_SIZE = 10;

        public BusinessController()
        {
            repository = new BusinessRepository();
            commons = new CommonRepository();
            agentRepository = new AgentRepository();
        }

        public ActionResult Index(int? page, string sortOrder)
        {
            return RedirectToAction("List", new { page = page, sortOrder = sortOrder });
        }

        public ActionResult List(int? page, string sortOrder)
        {
            ViewBag.SortParam = sortOrder;
            SetSearchViewBag();
            var models = from m in repository.All
                         where m.Language.LanguageName == CultureInfo.CurrentUICulture.Name
                         select m;

            switch (sortOrder)
            {
                case "hp":
                    models = models.OrderByDescending(b => b.asking);
                    break;
                case "lp":
                    models = models.OrderBy(b => b.asking);
                    break;
                default:
                    models = models.OrderByDescending(b => b.added_on);
                    break;
            }

            var listModels = models.AsEnumerable().Select(b => b.ToListModel());
            var pageNumber = page ?? 1;
            return View("Index", listModels.ToPagedList(pageNumber, PAGE_SIZE));
        }

        public ActionResult Search(BusinessSearchModel sm, int? page, string sortOrder)
        {
            ViewBag.SortParam = sortOrder;
            SetSearchViewBag();
            var models = from m in repository.FindBySearchModel(sm)
                         where m.Language.LanguageName == CultureInfo.CurrentUICulture.Name
                         select m;

            switch (sortOrder)
            {
                case "hp":
                    models = models.OrderByDescending(b => b.asking);
                    break;
                case "lp":
                    models = models.OrderBy(b => b.asking);
                    break;
                default:
                    models = models.OrderByDescending(b => b.added_on);
                    break;
            }

            var listModels = models.AsEnumerable().Select(b => b.ToListModel());
            var pageNumber = page ?? 1;
            return View("Index", listModels.ToPagedList(pageNumber, PAGE_SIZE));
        }

        public ActionResult Detail(int id)
        {
            var model = repository.Find(id);
            return View(model);
        }

        [NoMembershipAuthorize]
        public ActionResult Admin(int? page, string sortOrder, string language)
        {
            var all = repository.All;

            // Apply language filter
            if (language != "all" && !String.IsNullOrEmpty(language))
            {
                if (language == "en")
                    all = all.Where(b => b.Language.LanguageName == "en-AU");
                else
                    all = all.Where(b => b.Language.LanguageName == "zh-CN");
            }

            // Apply sorter
            ViewBag.TitleSortParam = String.IsNullOrEmpty(sortOrder) ? "td" : "";
            ViewBag.DateSortParam = sortOrder == "da" ? "dd" : "da";
            switch (sortOrder)
            {
                case "td":
                    all = all.OrderByDescending(m => m.title);
                    break;
                case "da":
                    all = all.OrderBy(m => m.added_on);
                    break;
                case "dd":
                    all = all.OrderByDescending(m => m.added_on);
                    break;
                default:
                    all = all.OrderBy(m => m.title);
                    break;
            }

            var models = all.AsEnumerable().Select(b => b.ToListModel());
            var pageNumber = page ?? 1;
            return View("AdminIndex", models.ToPagedList(pageNumber, PAGE_SIZE));
        }

        [NoMembershipAuthorize]
        public ActionResult Create()
        {
            var model = new Business();
            SetViewBag(model);
            return View(model);
        }

        [HttpPost, NoMembershipAuthorize]
        public ActionResult Create(Business model, IEnumerable<HttpPostedFileBase> attachments)
        {
            var cusr = Session["_CUSR"] as SessionUser;
            if (cusr == null) throw new ArgumentException("SessionUser");

            model.added_by = (byte)cusr.ID;
            model.added_on = DateTime.Now;

            try
            {
                if (attachments != null)
                {
                    foreach (var item in attachments)
                    {
                        if (item != null && item.ContentLength > 0)
                        {
                            var filename = Path.GetFileName(item.FileName).ToLower();
                            var dirpath = "~/Uploads/Business/" + GetFolderName(model);
                            var directory = Server.MapPath(dirpath);

                            if (!Directory.Exists(directory))
                                Directory.CreateDirectory(directory);

                            string path = Path.Combine(directory, filename);
                            string relPath = Path.Combine(dirpath, filename);
                            item.SaveAs(path);

                            model.Attachments.Add(new ProspectRealEstate.Web.Models.Attachment()
                            {
                                added_by = (byte)cusr.ID,
                                added_on = DateTime.Now,
                                Business = model,
                                file_location = relPath,
                                type = "image"
                            });
                        }
                    }
                }

                ModelState.Remove("Attachments");

                if (ModelState.IsValid)
                {
                    repository.InsertOrUpdate(model);
                    repository.SubmitChanges();
                    return RedirectToAction("Edit", new { id = model.ID });
                }
                else
                {
                    return View();
                }
            }
            catch (Exception ex)
            {
                throw;
            }
        }

        [NoMembershipAuthorize]
        public ActionResult Edit(int id)
        {
            var model = repository.Find(id);
            SetViewBag(model);
            return View(model);
        }

        [HttpPost, NoMembershipAuthorize]
        public ActionResult Edit(int id, IEnumerable<HttpPostedFileBase> attachments, FormCollection collection)
        {
            var cusr = Session["_CUSR"] as SessionUser;

            var model = repository.Find(id);
            try
            {
                if (attachments != null)
                {
                    foreach (var item in attachments)
                    {
                        if (item != null && item.ContentLength > 0)
                        {
                            var filename = Path.GetFileName(item.FileName).ToLower();
                            var dirpath = "~/Uploads/Business/" + GetFolderName(model);
                            var directory = Server.MapPath(dirpath);

                            if (!Directory.Exists(directory))
                                Directory.CreateDirectory(directory);

                            string path = Path.Combine(directory, filename);
                            string relPath = Path.Combine(dirpath, filename);
                            item.SaveAs(path);

                            var numOfAttachments = model.Attachments.Count(a => a.file_location == relPath);
                            if (numOfAttachments > 0)
                            {
                                var ex = model.Attachments.FirstOrDefault(a => a.file_location == relPath);
                                ex.modified_by = (byte)cusr.ID;
                                ex.modified_on = DateTime.Today;
                            }
                            else
                            {
                                model.Attachments.Add(new ProspectRealEstate.Web.Models.Attachment()
                                {
                                    added_by = (byte)cusr.ID,
                                    added_on = DateTime.Now,
                                    Business = model,
                                    file_location = relPath,
                                    type = "image"
                                });
                            }
                        }
                    }
                }
                model.modified_by = (byte)cusr.ID;
                model.modified_on = DateTime.Now;

                UpdateModel(model, collection);
                repository.SubmitChanges();
            }
            catch (Exception)
            {
                SetViewBag(model);
                return View(model);
            }
            SetViewBag(model);
            return View(model);
        }

        [HttpPost, NoMembershipAuthorize]

ProspectRealEstate.Web/Views/Business/AdminIndex.cshtml
@model PagedList.IPagedList<ProspectRealEstate.Web.Models.ViewModels.BusinessListModel>
@{
    ViewBag.Title = "Business management - Prospect Real Estate Admin";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@using (@Html.BeginForm("Admin", null, FormMethod.Get, new { style = "float: left" }))
{
    <label class="radio inline">
        @Html.RadioButton("language", "all", true, new { onclick = "document.forms[0].submit()" })
        All
    </label>
    <label class="radio inline">
        @Html.RadioButton("language", "en", new { onclick = "document.forms[0].submit()" })
        English only
    </label>
    <label class="radio inline">
        @Html.RadioButton("language", "cn", new { onclick = "document.forms[0].submit()" })
        Chinese only
    </label>
}

<div class="submit-button">
    @Html.ActionLink("Add", "Create", null, new { @class = "btn btn-primary pull-right" })
</div>

<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>#</th>
            <th>
                @Html.ActionLink("Title", "Admin", new { sortOrder = ViewBag.TitleSortParam })
            </th>
            <th>
                @Html.ActionLink("Added On", "Admin", new { sortOrder = ViewBag.DateSortParam })
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in @Model)
        {
            <tr>
                <td>
                    @if (item.IsFeatured)
                    {
                        <i class="icon-star"></i>
                    }
                    @item.ID
                </td>
                <td>@item.Title</td>
                <td>@item.AddedOn.ToShortDateString()</td>
                <td class="active-archive-button-group">
                    @Html.ActionLink("Edit", "Edit", "Business", new { id = @item.ID }, new { @class = "btn" })
                    @if (item.Status != "archived")
                    {
                        <a class="btn btn-danger archive-button" data-key="@item.ID">Archive</a>
                    }
                    else
                    {
                        <a class="btn btn-success activate-button" data-key="@item.ID">Activate</a>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>
<script type="text/javascript">
    $(function () {
        $('.active-archive-button-group').on('click', '.archive-button', function () {
            var $this = $(this)
              , model = {
                  ID: $this.data("key")
              };

            $.ajax({
                url: '/en-AU/Business/SetArchive',
                type: 'POST',
                data: model,
                success: function (result) {
                    if (result === 'success') {
                        $this.attr('class', 'btn btn-success activate-button');
                        $this.text('Activate');
                    }
                }
            });
        });

        $('.active-archive-button-group').on('click', '.activate-button', function () {
            var $this = $(this)
              , model = {
                  ID: $this.data("key")
              }

            $.ajax({
                url: '/en-AU/Business/SetActive',
                type: 'POST',
                data: model,
                success: function (result) {
                    if (result === 'success') {
                        $this.attr('class', 'btn btn-danger archive-button');
                        $this.text('Archive');
                    }
                }
            });
        });
    });
</script>

ProspectRealEstate.Web/Views/Business/Create.cshtml
@{
    ViewBag.Title = "Add a new business - Prospect Real Estate Admin";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@Html.Partial("_BusinessForm")

ProspectRealEstate.Web/Views/Business/Detail.cshtml
@model ProspectRealEstate.Web.Models.Business
@using Resx = ProspectRealEstate.Web.Resources;
@{
    Layout = null;
}

<div id="gallery" class="gallery">
    <div class="prev" onclick="prev()"><i class="icon-chevron-left icon-white"></i></div>
    <ul class="photos" style="left: 0">
        @foreach (var item in Model.Attachments)
        {
            if (Model.Attachments.ToList().IndexOf(item) == 0)
            {
            <li style="margin-left: 120px;">
                <img src="@Url.Content(item.file_location)" alt="400x300" width="400" height="300" />
            </li>
            }
            else
            {
            <li>
                <img src="@Url.Content(item.file_location)" alt="400x300" width="400" height="300" />
            </li>
            }
        }
    </ul>
    <div class="next" onclick="next()"><i class="icon-chevron-right icon-white"></i></div>
</div>
<div class="clearfix"></div>
<div class="details">
    <div id="msgMailSent" class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">×</button>
        @Resx.Detail.Detail.ThankYouMessage
    </div>
    <div id="msgMailError" class="alert alert-error">
        <button type="button" class="close" data-dismiss="alert">×</button>
        @Resx.Detail.Detail.ErrorMessage
    </div>
    <div class="information inner-container">
        <p>@Model.description</p>
        <dl>
            <dt>@Resx.Home.Index.Location:</dt>
            <dd>
                <div>@Model.street, @Model.Suburb.name, @Model.postcode</div>
            </dd>

            <dt>@Resx.Home.Index.Category:</dt>
            <dd>
                <div>@Model.Category.name</div>
            </dd>

            <dt>@Resx.Detail.Detail.AskingPrice:</dt>
            <dd>
                <div>@Model.AskingPrice</div>
            </dd>

            @if (@Model.taking.HasValue)
            {
                <dt>@Resx.Detail.Detail.TakingPrice:</dt>
                <dd>
                    <div>@Model.TakingPrice</div>
                </dd>
            }

            @if (@Model.rent.HasValue)
            {
                <dt>@Resx.Detail.Detail.RentPrice:</dt>
                <dd>
                    <div>@Model.RentPrice</div>
                </dd>
            }

            @if (!String.IsNullOrEmpty(@Model.lease))
            {
                <dt>@Resx.Detail.Detail.LeasePrice:</dt>
                <dd>
                    <div>@Model.lease</div>
                </dd>
            }

        </dl>
    </div>
    <div class="inner-container">
        <h4>@Resx.Detail.Detail.Contact</h4>
        @if (Model.agent_id.HasValue)
        {
            <div class="agent">
                <strong>@Model.Agent.name</strong>
                <div>@Model.Agent.phone</div>
            </div>
        }
        @using (Html.BeginForm("SendQuery", null, FormMethod.Post, new
        {
            id = "formSendQuery",
            @class = "contacts"
        }))
        {
            if (Model.agent_id.HasValue)
            {
            @Html.Hidden("AgentName", Model.Agent.name)
            @Html.Hidden("AgentEmail", Model.Agent.email)
            }
            @Html.Hidden("Subject", String.Join(",", @Model.business_code + ": " + @Model.title, @Model.street, @Model.Suburb.name, @Model.postcode))
            <fieldset>
                <label>@Resx.Detail.Detail.YourName</label>
                @Html.TextBox("UserName", null, new { @class = "span2 required" })

                <label>@Resx.Detail.Detail.YourEmail</label>
                @Html.TextBox("UserEmail", null, new { @class = "span2 required email" })

                <label>@Resx.Detail.Detail.Message</label>
                @Html.TextArea("Message",
                new
                {
                    @class = "span2 required",
                    rows = "3"
                })
            </fieldset>
            <input type="button" class="btn btn-primary" value="@Resx.Detail.Detail.SendMyQuery" onclick="sendUserQuery()" />
        }
    </div>
    <div class="clearfix"></div>
</div>
<script type="text/javascript">
    function prev() {
        var photos = $('.photos');
        var leftValue = parseInt(photos.css('left'));
        if (leftValue / 432 < 0) {
            photos.animate({
                left: '+=432px'
            }, 500);
        }
    }

    function next() {
        var photos = $('.photos');
        var leftValue = parseInt(photos.css('left'));
        var len = photos.find('li').length;
        if (leftValue / 432 > (-len + 1)) {
            photos.animate({
                left: '-=432px'
            }, 500);
        }
    }

    function sendUserQuery() {
        var formSendQuery = $('#formSendQuery');
        formSendQuery.validate();
        if (formSendQuery.valid()) {
            $.ajax({
                url: formSendQuery.attr("action"),
                type: formSendQuery.attr("method"),
                data: formSendQuery.serialize(),
                success: function (result) {
                    $('#msgMailSent').show().delay(3000).fadeOut();
                }
            });
        }
        else {
            $('#msgMailError').show().delay(5000).fadeOut();
            $('.details').scrollTop(0);
        }
    }
</script>

ProspectRealEstate.Web/Views/Business/Edit.cshtml
@model ProspectRealEstate.Web.Models.Business
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@Html.Partial("_BusinessForm")

ProspectRealEstate.Web/Views/Business/Index.cshtml
@model PagedList.IPagedList<ProspectRealEstate.Web.Models.ViewModels.BusinessListModel>
@using Resx = ProspectRealEstate.Web.Resources;
@{
    ViewBag.Title = "Businesses for Sale - Prospect Real Estate";
}

<div class="row">
    <div class="span8">
        <div class="content">
            <div>
                <h3>@Resx.Business.Index.BusinessesForSale</h3>
                @if (ViewContext.RouteData.Values["action"].ToString().ToLower() == "list")
                {
                    using (Html.BeginForm(null, null, FormMethod.Get))
                    {
                    <select name="sortOrder" onchange="document.forms[0].submit()">
                        <option value="">@Resx.Business.Index.SortResults</option>
                        <option value="lp" 
                                @if (ViewBag.SortParam == "lp")
                                { 
                                    @:selected = "selected" 
                                }>@Resx.Business.Index.LowestPrice
                        </option>
                        <option value="hp"
                                @if (ViewBag.SortParam == "hp")
                                { 
                                    @:selected = "selected" 
                                }>@Resx.Business.Index.HighestPrice
                        </option>
                        <option value="date"
                                @if (ViewBag.SortParam == "date")
                                { 
                                    @:selected = "selected" 
                                }>@Resx.Business.Index.Date
                        </option>
                    </select>
                    }
                }
                else
                {
                    <div>
                        <select id="selectSortOrder" name="sortOrder">
                            <option value="">@Resx.Business.Index.SortResults</option>
                            <option value="lp" 
                                @if (ViewBag.SortParam == "lp")
                                { 
                                    @:selected = "selected" 
                                }>@Resx.Business.Index.LowestPrice
                            </option>
                            <option value="hp"
                                @if (ViewBag.SortParam == "hp")
                                { 
                                    @:selected = "selected" 
                                }>@Resx.Business.Index.HighestPrice
                            </option>
                            <option value="date"
                                @if (ViewBag.SortParam == "date")
                                { 
                                    @:selected = "selected" 
                                }>@Resx.Business.Index.Date
                            </option>
                        </select>
                    </div>
                }
            </div>
            <ul class="biz-list">
                @foreach (var item in Model)
                {
                    <li class="list-item">
                        <div class="list-date">
                            <div class="month">@item.AddedOn.Month</div>
                            <div class="day">@item.AddedOn.Day</div>
                        </div>
                        <div class="figure">
                            @if (!String.IsNullOrEmpty(item.ThumbnailFilePath))
                            {
                                <img src="@Url.Content(@item.ThumbnailFilePath)" alt="4:3" width="160" height="120" />
                            }
                            else
                            {
                                <img src="" alt="4:3" width="160" height="120" />
                            }

                        </div>
                        <div class="info">
                            <div class="title">
                                <a href="Detail/@item.ID" class="dtlink">@item.Title</a>
                            </div>
                            <div class="meta">
                                <span class="location">@item.Location</span>
                                <span class="separator">|</span>
                                <span class="type">@item.Category</span>
                                <span class="separator">|</span>
                                <span class="asking-price">@item.AskingPrice</span>
                            </div>
                            <p class="desc">@item.Description</p>
                        </div>
                        <div class="clearfix"></div>
                    </li>
                }
            </ul>
            @Html.Partial("Pager")
        </div>
    </div>
    <div class="span4">
        <div class="search-biz">
            <h4 class="section-header">@Resx.Business.Index.FindABusiness</h4>
            @using (Html.BeginForm("Search", "Business", FormMethod.Get, new { id = "formSearchBusiness" }))
            {
                <fieldset>
                    <label>@Resx.Home.Index.Location</label>
                    @Html.ListBox("BusinessLocation", ViewBag.Suburbs as MultiSelectList,
                        new
                        {
                            @class = "chzn-select",
                            data_placeholder = "Choose suburbs..."
                        })
                    <label>@Resx.Home.Index.Category</label>
                    @Html.DropDownList("Category", ViewBag.Categories as SelectList)
                    <label>@Resx.Business.Index.AskingPrice</label>
                    <div style="margin-bottom: 20px;">
                        <span class="input-prepend">
                            <span class="add-on">$</span>
                            @Html.TextBox("MinAskingPrice", null, new { @class = "span1" })
                        </span>
                        <span style="padding: 0 10px; line-height: 30px">to</span>
                        <span class="input-prepend">
                            <span class="add-on">$</span>
                            @Html.TextBox("MaxAskingPrice", null, new { @class = "span1" })
                        </span>
                    </div>
                    <input id="searchSortOrder" name="sortOrder" type="hidden" />
                </fieldset>
                <button type="submit" class="btn btn-primary">@Resx.Home.Index.Search</button>
            }
        </div>
    </div>
    <div id="detail-modal" class="modal hide" data-remote="">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h3 class="modal-title"></h3>
        </div>
        <div class="modal-body"></div>
    </div>
</div>
<script src="@Url.Content("~/Content/js/vendor/chosen.jquery.min.js")"></script>
<link href="@Url.Content("~/Content/css/chosen.css")" rel="stylesheet" type="text/css" />
<script type="text/javascript">
    $('.chzn-select').chosen();

    $(function () {
        $('.dtlink').click(function () {
            var $this = $(this)
              , $modal = $('#detail-modal');

            $('#detail-modal .modal-title').text($this.text());
            $modal.data('remote', $this.attr('href'));
            $modal.modal();

            return false;
        });

        $('#detail-modal').on('hidden', function () {
            $(this).removeData('modal');
        });

        $('#selectSortOrder').change(function () {
            var $this = $(this);
            $('#searchSortOrder').val($this.val());
            $('#formSearchBusiness').submit();
        });
    });
</script>